apiVersion: v1
kind: Pod
metadata:
  namespace: kube-system
  name: etcd
spec:
  hostNetwork: true
  containers:
  - name: etcd
    image: {{.EtcdImage}}
    command:
    - etcd
    - --advertise-client-urls=https://{{.NodeIP}}:2379
    - --cert-file={{.PemKubernetes}}
    - --client-cert-auth
    - --data-dir={{.EtcdDataDirectory}}
    - --initial-advertise-peer-urls=https://{{.NodeIP}}:2380
    - --initial-cluster={{.EtcdCluster}}
    - --initial-cluster-state=new
    - --initial-cluster-token=etcd-cluster
    - --key-file={{.PemKubernetesKey}}
    - --listen-client-urls=https://{{.NodeIP}}:2379
    - --listen-peer-urls=https://{{.NodeIP}}:2380
    - --name={{.Name}}
    - --peer-cert-file={{.PemKubernetes}}
    - --peer-client-cert-auth
    - --peer-key-file={{.PemKubernetesKey}}
    - --peer-trusted-ca-file={{.PemCA}}
    - --trusted-ca-file={{.PemCA}}
    readinessProbe:
      exec:
        command:
        - /bin/sh
        - -ec
        - ETCDCTL_API=3 etcdctl 
          --endpoints=https://{{.NodeIP}}:2379 
          --cacert={{.PemCA}}
          --cert={{.PemKubernetes}}
          --key={{.PemKubernetesKey}}
          endpoint health
      initialDelaySeconds: 1
      timeoutSeconds: 5
      failureThreshold: 5
    livenessProbe:
      exec:
        command:
        - /bin/sh
        - -ec
        - ETCDCTL_API=3 etcdctl 
          --endpoints=https://{{.NodeIP}}:2379 
          --cacert={{.PemCA}}
          --cert={{.PemKubernetes}}
          --key={{.PemKubernetesKey}}
          endpoint health
      initialDelaySeconds: 10
      timeoutSeconds: 10
      failureThreshold: 5
    volumeMounts:
    - name: etcd-data-directory
      mountPath: {{.EtcdDataDirectory}}
    - name: pem-ca
      mountPath: {{.PemCA}}
      readOnly: true
    - name: pem-kubernetes
      mountPath: {{.PemKubernetes}}
      readOnly: true
    - name: pem-kubernetes-key
      mountPath: {{.PemKubernetesKey}}
      readOnly: true
  volumes:
  - name: etcd-data-directory
    hostPath:
      type: DirectoryOrCreate
      path: {{.EtcdDataDirectory}}
  - name: pem-ca
    hostPath:
      type: File
      path: {{.PemCA}}
  - name: pem-kubernetes
    hostPath:
      type: File
      path: {{.PemKubernetes}}
  - name: pem-kubernetes-key
    hostPath:
      type: File
      path: {{.PemKubernetesKey}}
