apiVersion: v1
kind: Pod
metadata:
  namespace: kube-system
  name: gobetween
  labels:
    cluster-relevant: "true"
spec:
  hostNetwork: true
  containers:
  - name: gobetween
    image: {{.GobetweenImage}}
    command:
    - /gobetween
    - -c
    - {{.Config}}
    resources:
      requests:
        cpu: 100m
    volumeMounts:
    - name: config
      mountPath: {{.Config}}
      readOnly: true
  volumes:
  - name: config
    hostPath:
      type: File
      path: {{.Config}}
