apiVersion: v1
kind: Pod
metadata:
  namespace: kube-system
  name: kube-scheduler
  labels:
    cluster-relevant: "true"
spec:
  hostNetwork: true
  containers:
  - name: kube-scheduler
    image: {{.KubernetesImage}}
    command:
    - kube-scheduler
    - --config={{.KubeSchedulerConfig}}
    livenessProbe:
      failureThreshold: 8
      httpGet:
        scheme: HTTP
        host: 127.0.0.1
        port: 10251
        path: /healthz
      initialDelaySeconds: 15
      timeoutSeconds: 15
    resources:
      requests:
        cpu: 100m
    volumeMounts:
    - name: kube-scheduler-config
      mountPath: {{.KubeSchedulerConfig}}
      readOnly: true
    - name: kube-scheduler-kubeconfig
      mountPath: {{.KubeSchedulerKubeconfig}}
      readOnly: true
  volumes:
  - name: kube-scheduler-config
    hostPath:
      type: File
      path: {{.KubeSchedulerConfig}}
  - name: kube-scheduler-kubeconfig
    hostPath:
      type: File
      path: {{.KubeSchedulerKubeconfig}}
